# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerbos < Formula
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"
  version "0.11.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/cerbos/cerbos/releases/download/v0.11.0/cerbos_0.11.0_Darwin_all.tar.gz"
    sha256 "f02f5c60e73b2a8e16621459e343f65bfdb81d60bec0773c27004afdf539d70d"

    def install
      bin.install "cerbos"
      bin.install "cerbosctl"
    end
    if Hardware::CPU.arm?
      url "https://github.com/cerbos/cerbos/releases/download/v0.11.0/cerbos_0.11.0_Darwin_arm64.tar.gz"
      sha256 "04ab48022ab95af84a90f3581b72813885ec73d1bf36a1ba48810ff0eb7b74a9"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.11.0/cerbos_0.11.0_Darwin_x86_64.tar.gz"
      sha256 "a0a942785a13c774dff37f70a4268547c1ce997e2ecf83f9ac2e302839da53b1"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.11.0/cerbos_0.11.0_Linux_x86_64.tar.gz"
      sha256 "8ab93c4d53863cf6c8025bdbec4d35ccac87d26165e424baf5dd766e0f1b0b3f"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerbos/cerbos/releases/download/v0.11.0/cerbos_0.11.0_Linux_arm64.tar.gz"
      sha256 "7f86e5a94921f85ba60cf11631c3f72d48cc7d9ed472af310ab70098a3d7a4d4"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end
end
