# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerbos < Formula
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cerbos/cerbos/releases/download/v0.12.0/cerbos_0.12.0_Darwin_arm64.tar.gz"
      sha256 "d4c4ca023aa68398e4cdaf0bcd6d9037fae46ad84e6914422877e1b90f51b139"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.12.0/cerbos_0.12.0_Darwin_x86_64.tar.gz"
      sha256 "e6130f16640dde2f1aa9cca6c9c00ae29611a4d29210a708c1593d33dc5216e9"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.12.0/cerbos_0.12.0_Linux_x86_64.tar.gz"
      sha256 "963331b8dff38c3dc2829f8cb1ee5f9c7d2d823bac4fdee2e57e1b9e9fe44eb1"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerbos/cerbos/releases/download/v0.12.0/cerbos_0.12.0_Linux_arm64.tar.gz"
      sha256 "909f03e9694ba3841956bc68a5921bfef9f250a2b6446df53455007b4f1c09d6"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end
end
