# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerbos" do
  version "0.54.0"

  on_macos do
    on_intel do
      sha256 "1892068b4ff80fcbb5f1da4df085066ade7aa3663630600ea0022a4572934d85"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
    on_arm do
      sha256 "6a56c27c76f7098b5e5d3b009377d12662295d9b2d2d4faa44feb4a7868f9475"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
  end

  on_linux do
    on_intel do
      sha256 "68ce48355cf1df125da9ff2b6c0b07d35781155d3aa1707707c381c2e454f156"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
    on_arm do
      sha256 "5f350e2c65206c97b5f24a61f507862b68a63f9b0904e380ed1755f93c3e0e99"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
  end

  name "cerbos"
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerbos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerbos"]
    end
  end

  # No zap stanza required

end
