# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerbos" do
  name "cerbos"
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"
  version "0.50.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerbos"

  on_macos do
    on_intel do
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
      sha256 "9d161ade1d554271f41ff016f91162b4a18ab7746988e8d04e6f06d98b3a9d5a"
    end
    on_arm do
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
      sha256 "f9ca4ac1d3e86c1640da4230412890d4ce762dfdf921707fcf9a17d6c3c765f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
      sha256 "c9bc8f7670693423b59303c6d93ebf694f746712c18a01708fab6dc7f69381ea"
    end
    on_arm do
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
      sha256 "85fbaad8f86834ccdffd537ccdddcab69a51a277d3d1b0c5d97feecb2835f6b3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerbos"]
    end
  end

  # No zap stanza required
end
