# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerbos" do
  version "0.53.0"

  on_macos do
    on_intel do
      sha256 "cbb6abcc28b440b4783d82d792a72486f9a799f88d3c35c6dd3c7ee1a54c4b71"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
    on_arm do
      sha256 "9fee515616f0882efa5ae13b3796dd7f8bbb6d80ace302052924d560c8a2aa05"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
  end

  on_linux do
    on_intel do
      sha256 "56427176bd2e5e676097f9a08743ed211e7c0123af1e71a48f94d497e3c9e131"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
    on_arm do
      sha256 "c8adbd22e41676d8957d24af11ebb3dec312eabf0361731f9bef0604144af493"
      url "https://github.com/cerbos/cerbos/releases/download/v#{version}/cerbos_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/cerbos/homebrew-tap"
    end
  end

  name "cerbos"
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerbos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerbos"]
    end
  end

  # No zap stanza required

end
