# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerbos < Formula
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"
  version "0.15.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.15.0/cerbos_0.15.0_Darwin_x86_64.tar.gz"
      sha256 "fba6817f0e4704c425eb210a05c11df99b2a7d4cc4ed6cf49d6181b5b6463ba2"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cerbos/cerbos/releases/download/v0.15.0/cerbos_0.15.0_Darwin_arm64.tar.gz"
      sha256 "57b0fb4f52eaed3675b66a02e8297547c749e2253cff80673439043b2a1dc708"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.15.0/cerbos_0.15.0_Linux_x86_64.tar.gz"
      sha256 "a9b5a4c477cff13eba031b819c28525bccbce78215e770f8357ed07833435476"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerbos/cerbos/releases/download/v0.15.0/cerbos_0.15.0_Linux_arm64.tar.gz"
      sha256 "4c445c768e06765e4b533e745c809a15ccf97f851a0fe170c3be22935ae24c23"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end
end
