# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cerbos < Formula
  desc "Cerbos is the open core, language-agnostic, scalable authorization solution that makes user permissions and authorization simple to implement and manage by writing context-aware access control policies for your application resources."
  homepage "https://cerbos.dev"
  version "0.21.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cerbos/cerbos/releases/download/v0.21.0/cerbos_0.21.0_Darwin_arm64.tar.gz"
      sha256 "3b5f89b97cd7a3bbf506bd61d97f6a8a903ae90df8f01475cca1f9e70c3d79c5"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.21.0/cerbos_0.21.0_Darwin_x86_64.tar.gz"
      sha256 "4df6720dcef41f179c2e21980271b8cd8d0850bd98e0910a3b9682fcf6eb0200"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cerbos/cerbos/releases/download/v0.21.0/cerbos_0.21.0_Linux_arm64.tar.gz"
      sha256 "bf27c1d07761def48bd48c22cb2ec4d51cffd6a3c0091419a4a2283d1d4d2021"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cerbos/cerbos/releases/download/v0.21.0/cerbos_0.21.0_Linux_x86_64.tar.gz"
      sha256 "f4aa746de798df6f5a0e660a6ff9e931f5cffadaf696c120508c56712c88dc7d"

      def install
        bin.install "cerbos"
        bin.install "cerbosctl"
      end
    end
  end
end
